# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Leonardo Calzada"                                # Your name
  description: "PhD Candidate in Geography, Rutgers University"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "News"
        href: cv/index.qmd
      - text: "Contact me"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/le_calzada
      - icon: github
        href: https://github.com/leocalzada
      - icon: instagram
        href: https://www.instagram.com/lecalzada/
      - icon: envelope
        aria-label: email
        href: "mailto:leonardo.calzada@rutgers.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; CC-By Leonardo Calzada</span>
    center: |
    
    right: |
      <span class="faux-block">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>, with theme from <a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">marvinschmitt </a> </span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      dark: darkly
    css: html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true